### ISSUE TITLE
Huge memory consumption when importing large folder

### ISSUE THREAD

**Issue by eye-wave** [basharovV/musicat#13]
hello again!

i tried to import all my music at once, but the app ate all of my 16gigs of ram and swap in no time, causing the whole system to hang up.
This is how it looks like after i tried again, after i stopped it before anything bad happened.
![image](https://github.com/user-attachments/assets/7f8fbe27-c8ef-49c6-833a-126c5e13cb1c)

i tried importing all of my albums one by one next. didn't encounter any issues then.

**Comment by basharovV** [comment]
I think I've addressed the main issue here, was sending artworks for caching over IPC which is too much data! Now album aggregation and artwork caching happens together with the metadata parsing which is much better indeed! I imported a library of 1600 songs and RAM usage stayed consistent around ~216MB. Can you give it another go?

**Comment by eye-wave** [comment]
Works like a charm now
