### ISSUE TITLE
Can't type certain letter in text inputs

### ISSUE THREAD

**Issue by eye-wave** [basharovV/musicat#14]
Probably it has something to do with shortcuts overriding keydown events.
anyways here are all the keys that don't work for me

<kbd>Q</kbd>, <kbd>A</kbd> and <kbd>L</kbd>

**Comment by basharovV** [comment]
I can reproduce this on Linux but not on macOS for some reason (the menu shortcut isn't being triggered when typing in a focused input field). I've opened a Tauri bug here: https://github.com/tauri-apps/tauri/issues/10482

**Comment by basharovV** [comment]
Closing as I've changed the shortcuts to be Alt+Q, Alt+A and Alt+L
