### ISSUE TITLE
Player does not start on Windows

### ISSUE THREAD

**Issue by rondlite** [basharovV/musicat#2]
Player on windows will stay on 00:00 (does not play).
Latest version 0.5

I checked console and it says the asset://localhost scheme is not supported
ERR_UNKOWN_URL_SCHEME

Investigating if I can fix it myself, one reason that it would fail in the first place is the backslashes in windows filepath, while URL should have forward slashes. I did a replace, but that not yet fixed the unknown scheme error.

**Comment by JCGithu** [comment]
Can second this. Player does load (after installing additional packages listed in my other issue), but then I get this same issue trying to play any files.

**Comment by basharovV** [comment]
Thanks for reporting. I thought Tauri would handle this with `convertFileSrc`. I'll take a look at this, once I get access to a Windows machine that is.

**Comment by rondlite** [comment]
The audioplayer does not use `convertFileSrc` but a direct link to `asset.localhost`. 
I changed, but now I am running into CORS issue, almost there..

**Comment by basharovV** [comment]
Finally got my Windows environment set up for this. Indeed, `convertFileSrc` was not being used and the `audio` element didn't have `crossOrigin='anonymous'`. Tracks should be playing now, but overall the Windows/Linux versions of this app need some love. Will add this in the next release :) Merry Christmas 🎄

**Comment by rondlite** [comment]
@basharovV great fix, just in time for Mariah Carey
