### ISSUE TITLE
Fix linux build, update deps

### ISSUE THREAD

**Issue by puterproblems** [basharovV/musicat#25]
Sorry to include two separate things in the same issue, but I did the update deps bit of housekeeping as part of debugging and nothing broke (or got better) but it seems helpful overall. As for fixing the linux build, things did not work for my rather mundane Pop_OS system (plenty of entirely unhelpful panics from the compiler). I did a poor job of documenting my process, but the overall cause was macos-specific libraries such as objc2 (and the adjacent block2), and window-vibrancy not building on linux in addition to this line: `println!("cargo:rustc-link-lib=framework=MediaPlayer");` in `build.rs`.

After all that work the music player is working well on my system now and should hopefully be much easier to build for other linux users! You'll have to tell me if everything still works as expected on the macos side.

I'll create and link a PR with my changes.

**Comment by basharovV** [comment]
Much appreciated! I need to be more careful when doing platform-specific features :) Also happy to move to Tauri v2 stable, I'll update the plugins to `2.0.0` as well.
