### ISSUE TITLE
Package.json missing "rollup-plugin-node-polyfills" and "mousetrap"

### ISSUE THREAD

**Issue by JCGithu** [basharovV/musicat#3]
This causes an issue when running npm tauri run dev on Windows.

**Comment by basharovV** [comment]
I'm not getting this error. Are you using Node version 18? Sorry I should have specified this in package.json

**Comment by JCGithu** [comment]
v21.4.0 - not sure how that links to the specific packages though, are they just missing as they're installed locally?
