### ISSUE TITLE
Issues with playlist functionality and album display

### ISSUE THREAD

**Issue by HareToAme** [basharovV/musicat#4]
Thank you for developing this exceptional application! I have encountered two persistent issues that I would like to bring to your attention:

1. After the last song in a playlist finishes playing, the application continues to play songs, but the player interface becomes unresponsive(e.g. the play button does not work). In fact, the play button deactivates whenever the next song starts playing.
![1](https://github.com/basharovV/musicat/assets/85005258/07ab42ec-8017-4eaf-a820-cc40f40c4a97)

2. I'm playing the songs in the playlist, and then I enter the album interface. If the playlist moves to the next song at this time, the title on the album interface successfully updates to display the name of the album that the next song belongs to. However, the displayed tracklist on the album interface still corresponds to the previous song's album.
![2](https://github.com/basharovV/musicat/assets/85005258/31916cfa-eb29-4f65-b97d-f5cab12c7b17)

Additionally, I have a small suggestion. Would it be possible to add support for opening `.cue` text files and importing track splits into the playlist? Similar to the functionality found in foobar2000.

The app version I'm using is <https://github.com/basharovV/musicat/tree/8fd5660ecdb534628c441d497c6ab53f49e78669>

**Comment by basharovV** [comment]
Glad you're enjoying the app! Thanks for reporting, fixed on the main branch, and will be available in the next release. 

I did start working on cue sheets but parked it for now as I wasn't too happy with the approach. I'm sure I'll come back to it at some point. In the meantime, I highly recommend [fre:ac](https://www.freac.org), it can split output into multiple files automatically, just drag a folder into it.
