### ISSUE TITLE
[weird]: can't successfully run `npm run tauri dev` with `main` branch

### ISSUE THREAD

**Issue by daiyam** [basharovV/musicat#49]
Hi,

I'm not sure what's going on... I tried everything, removing all cache, database and configs.
But I can't run `npm run tauri dev` on the `main` branch, I get a blank window with the main error likely to be `[Error] [HMR][Svelte] – "Unrecoverable HMR error in <CanvasLibrary>: next update will trigger a full reload"`.
Weirdly, I can run on 2 of my PR: #37 and #47

I was wondering if you had this issue before...

Here the PR I would like to submit:
![Screenshot 2024-12-17 at 21 08 24](https://github.com/user-attachments/assets/18b20406-ebb4-489d-8f25-4ebc7c8b3d99)
It's ready but I just need to port it back to `main` branch...

**Comment by basharovV** [comment]
Hard to say, maybe a non-existing module import? is there a branch/commit I can try it out on?

**Comment by daiyam** [comment]
Ok, I've got it back by running:
```
rm -r "/Users/baptiste/Library/HTTPStorages/com.vbapps.musicat.binarycookies" "/Users/baptiste/Library/WebKit/com.vbapps.musicat" "/Users/baptiste/Library/Application Support/Musicat" "/Users/baptiste/Library/WebKit/Musicat" "/Users/baptiste/Library/Caches/Musicat" "/Users/baptiste/Library/Preferences/Musicat.plist" "/Users/baptiste/Library/Logs/Musicat" "/Users/baptiste/Library/Caches/Musicat" "/Users/baptiste/Library/Logs/com.vbapps.musicat"
```

Something must have went haywire somewhere...
