### ISSUE TITLE
How do you run the dmg file on windows

### ISSUE THREAD

**Issue by Enobongime79** [basharovV/musicat#7]
i tried extracting it and it couldnt find the executable file

**Comment by basharovV** [comment]
DMGs are macOS only. For Windows I'm afraid you'll have to build it locally using `npm run tauri build`, and for the next release I'll include the Windows build in the release, although I haven't given attention to the Windows build so expect it to be a little rough around the edges!

**Comment by Enobongime79** [comment]
Thanks
